// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjYF0wYIjdgTQUv6diFiINRvGSz7hx-jg',
    appId: '1:187322154568:web:bddd9fa75aeec48871e27d',
    messagingSenderId: '187322154568',
    projectId: 'fitnessapp-93143',
    authDomain: 'fitnessapp-93143.firebaseapp.com',
    storageBucket: 'fitnessapp-93143.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEJDh1rXbHciBZVmaLrDbB-YS3XA5jp8',
    appId: '1:187322154568:android:36d42a596a40f4ec71e27d',
    messagingSenderId: '187322154568',
    projectId: 'fitnessapp-93143',
    storageBucket: 'fitnessapp-93143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDG8lOJsQYqOoieFQs1iEFe4ykRlSxdk',
    appId: '1:187322154568:ios:951f3ca7348f83f171e27d',
    messagingSenderId: '187322154568',
    projectId: 'fitnessapp-93143',
    storageBucket: 'fitnessapp-93143.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDG8lOJsQYqOoieFQs1iEFe4ykRlSxdk',
    appId: '1:187322154568:ios:951f3ca7348f83f171e27d',
    messagingSenderId: '187322154568',
    projectId: 'fitnessapp-93143',
    storageBucket: 'fitnessapp-93143.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjYF0wYIjdgTQUv6diFiINRvGSz7hx-jg',
    appId: '1:187322154568:web:249bd2b4d56415c871e27d',
    messagingSenderId: '187322154568',
    projectId: 'fitnessapp-93143',
    authDomain: 'fitnessapp-93143.firebaseapp.com',
    storageBucket: 'fitnessapp-93143.firebasestorage.app',
  );
}
